ElectronsMatchingBarrel:
  sample: DYLL_M50
  version: V31
  match_test_to_ref: True
  reference_object:
    object: "part_e"
    x_arg: "Pt"
    label: "Gen Electrons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "abs({eta}) < 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    EG:default: "Pt"
    tkElectron:NoIso: "Pt"
    tkElectron:Iso: "Pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (Barrel)"
  binning:
    min: 0
    max: 100
    step: 3

ElectronsMatchingEndcap:
  sample: DYLL_M50
  version: V31
  match_test_to_ref: True
  reference_object:
    object: "part_e"
    x_arg: "Pt"
    label: "Gen Electrons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "abs({eta}) > 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    EG:default: "Pt"
    tkElectron:NoIso: "Pt"
    tkElectron:Iso: "Pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (Endcap)"
  binning:
    min: 0
    max: 100
    step: 3
