JetMatching_Eta_Pt40To100_ExtendedVsRegular:
  sample: TT
  version: V31
  match_test_to_ref: True
  reference_object: 
    object: "jet"
    x_arg: "Eta"
    label: "Gen Jets"
    cuts:
      event:
        - "{pt} > 40"
        - "{pt} < 100"
      object:
        - "abs({eta}) < 5"
  test_objects:
    seededConePuppiJet:default: "Eta"
    seededConeExtendedPuppiJet:default: "Eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (40-100 GeV)"
  binning:
    min: -5
    max: 5
    step: 0.25

JetMatching_Eta_Pt100ToInf_ExtendedVsRegular:
  sample: TT
  version: V31
  match_test_to_ref: True
  reference_object: 
    object: "jet"
    x_arg: "Eta"
    label: "Gen Jets"
    cuts:
      event:
        - "{pt} > 100"
      object:
        - "abs({eta}) < 5"
  test_objects:
    seededConePuppiJet:default: "Eta"
    seededConeExtendedPuppiJet:default: "Eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (>100 GeV)"
  binning:
    min: -5
    max: 5
    step: 0.25

JetMatching_Eta_Pt30ToInf_genBJets:
  sample: TT
  version: V31
  match_test_to_ref: True
  reference_object: 
    object: "jet"
    x_arg: "Eta"
    label: "Gen Jets"
    cuts:
      event:
        - "{pt} > 30"
        - "abs({partonflavour}) == 5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    seededConeExtendedPuppiJet:bjetnn: "Eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (>30 GeV)"
  binning:
    min: -2.4
    max: 2.4
    step: 0.25

JetMatching_Eta_Pt30ToInf_genNotBJets:
  sample: TT
  version: V31
  match_test_to_ref: True
  reference_object: 
    object: "jet"
    x_arg: "Eta"
    label: "Gen Jets"
    cuts:
      event:
        - "{pt} > 30"
        - "abs({partonflavour}) != 5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    seededConeExtendedPuppiJet:bjetnn: "Eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (>30 GeV)"
  binning:
    min: -2.4
    max: 2.4
    step: 0.25

JetMatching_Pt_Pt30ToInf_genBJets:
  sample: TT
  version: V31
  match_test_to_ref: True
  reference_object: 
    object: "jet"
    x_arg: "Pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({partonflavour}) == 5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    seededConeExtendedPuppiJet:bjetnn: "Pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency"
  binning:
    min: 30
    max: 200
    step: 10

JetMatching_Pt_Pt30ToInf_genNotBJets:
  sample: TT
  version: V31
  match_test_to_ref: True
  reference_object: 
    object: "jet"
    x_arg: "Pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({partonflavour}) != 5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    seededConeExtendedPuppiJet:bjetnn: "Pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency"
  binning:
    min: 30
    max: 200
    step: 10
