JetMatching_Eta_Pt40To100:
  sample: TT
  version: V31
  match_test_to_ref: True
  reference_object: 
    object: "jet"
    x_arg: "Eta"
    label: "Gen Jets"
    cuts:
      event:
        - "{pt} > 40"
        - "{pt} < 100"
      object:
        - "abs({eta}) < 5"
  test_objects:
    phase1PuppiJet:default: "Eta"
    seededConePuppiJet:default: "Eta"
    caloJet:default: "Eta"
    trackerJet:default: "Eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (40-100 GeV)"
  binning:
    min: -5
    max: 5
    step: 0.25

JetMatching_Eta_Pt100ToInf:
  sample: TT
  version: V31
  match_test_to_ref: True
  reference_object: 
    object: "jet"
    x_arg: "Eta"
    label: "Gen Jets"
    cuts:
      event:
        - "{pt} > 100"
      object:
        - "abs({eta}) < 5"
  test_objects:
    phase1PuppiJet:default: "Eta"
    seededConePuppiJet:default: "Eta"
    caloJet:default: "Eta"
    trackerJet:default: "Eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (>100 GeV)"
  binning:
    min: -5
    max: 5
    step: 0.25

JetMatching_Eta_Pt100ToInf_extEta:
  sample: TT
  version: V31
  match_test_to_ref: True
  reference_object: 
    object: "jet"
    x_arg: "Eta"
    label: "Gen Jets"
    cuts:
      event:
        - "{pt} > 100"
      object:
        - "abs({eta}) < 7"
  test_objects:
    caloJet:default: "Eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (>100 GeV)"
  binning:
    min: -5.5
    max: 5.5
    step: 0.25