JetTurnonFwd_3p7to7:
  sample: TT
  version: V31
  match_test_to_ref: True
  reference_object:
    object: "jet"
    x_arg: "Pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({eta}) > 3.7"
      object:
        - "abs({eta}) < 7"
  test_objects:
    #phase1PuppiJet:default:forward: "Pt"
    seededConePuppiJet:default:forward: "Pt"
  thresholds: [50,100]
  scalings:
    method: "naive"
    threshold: 0.95
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: r'Trigger Efficiency (<threshold> GeV, $3.6<\eta<6$)'
  binning:
    min: 0
    max: 300
    step: 10
