MuonsTrigger_Barrel:
  sample: DYLL_M50
  version: V31
  match_test_to_ref: True
  reference_object:
    object: "part_mu"
    x_arg: "Pt"
    label: "Gen Muons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
      object:
        - "abs({eta}) < 0.83"
  test_objects:
    gmtMuon:default:barrel: "Pt"
    gmtTkMuon:default:barrel: "Pt"
  xlabel: "Gen. pT (GeV)"
  ylabel: "Trigger Efficiency (barrel, L1 $p_T > 20$ GeV)"
  thresholds: [20, 25]
  scalings:
    method: "naive"
    threshold: 0.95
  binning:
    min: 0
    max: 50
    step: 1.5

MuonsTrigger_Overlap:
  sample: DYLL_M50
  version: V31
  match_test_to_ref: True
  reference_object:
    object: "part_mu"
    x_arg: "Pt"
    label: "Gen Muons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
      object:
        - "abs({eta}) > 0.83"
        - "abs({eta}) < 1.24"
  test_objects:
    gmtMuon:default:overlap: "Pt"
    gmtTkMuon:default:overlap: "Pt"
  xlabel: "Gen. pT (GeV)"
  ylabel: "Trigger Efficiency (overlap, L1 $p_T > 20$ GeV)"
  thresholds: [20, 25]
  scalings:
    method: "naive"
    threshold: 0.95
  binning:
    min: 0
    max: 50
    step: 1.5

MuonsTrigger_Endcap:
  sample: DYLL_M50
  version: V31
  match_test_to_ref: True
  reference_object:
    object: "part_mu"
    x_arg: "Pt"
    label: "Gen Muons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
      object:
        - "abs({eta}) > 1.24"
  test_objects:
    gmtMuon:default:endcap: "Pt"
    gmtTkMuon:default:endcap: "Pt"
  xlabel: "Gen. pT (GeV)"
  ylabel: "Trigger Efficiency (endcap, L1 $p_T > 20$ GeV)"
  thresholds: [20, 25]
  scalings:
    method: "naive"
    threshold: 0.95
  binning:
    min: 0
    max: 50
    step: 1.5
