PhotonsTrigger_Barrel:
  sample: Hgg
  version: V31
  match_test_to_ref: True
  reference_object:
    object: "part_gamma"
    x_arg: "Pt"
    label: "Gen Photons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "abs({eta}) < 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    EG:default:barrel: "Pt"
    tkPhoton:NoIso:barrel: "Pt"
    tkPhoton:Iso:barrel: "Pt"
  thresholds: [10, 20, 30, 40]
  scalings:
    method: "naive"
    threshold: 0.95
  xlabel: "Gen. pT (GeV)"
  ylabel: "Trigger Efficiency (barrel, L1 $p_T > <threshold>$ GeV)"
  binning:
    min: 0
    max: 100
    step: 1.5

PhotonsTrigger_Endcap:
  sample: Hgg
  version: V31
  match_test_to_ref: True
  reference_object:
    object: "part_gamma"
    x_arg: "Pt"
    label: "Gen Photons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "abs({eta}) > 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    EG:default:endcap: "Pt"
    tkPhoton:NoIso:endcap: "Pt"
    tkPhoton:Iso:endcap: "Pt"
  thresholds: [10, 20, 30, 40]
  scalings:
    method: "naive"
    threshold: 0.95
  xlabel: "Gen. pT (GeV)"
  ylabel: "Trigger Efficiency (endcap, L1 $p_T > <threshold>$ GeV)"
  binning:
    min: 0
    max: 100
    step: 1.5
