JetMatchingForward_3p7to7:
  sample: TT
  default_version: V30
  reference_object:
    object: "jet"
    suffix: "Pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({eta}) > 3.7"
      object:
        - "abs({eta}) < 5"
  test_objects:
    # phase1PuppiJet:
    #   match_dR: 0.3
    #   suffix: "Pt"
    #   label: "Histogrammed PuppiJet"
    #   cuts:
    #     - "abs({eta}) < 7"
    # seededConePuppiJet:
    #   match_dR: 0.35
    #   suffix: "Pt"
    #   label: "Seeded Cone PuppiJet"
    #   cuts:
    #     - "abs({eta}) < 7"
    caloJet:
      match_dR: 0.3
      suffix: "Pt"
      label: "Calo Jet"
      cuts:
        - "abs({eta}) < 7"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (forward)"
  binning:
    min: 0
    max: 300
    step: 5

JetMatchingBarrel:
  sample: TT
  default_version: V30
  reference_object:
    object: "jet"
    suffix: "Pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({eta}) < 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    # caloJet:
    #   match_dR: 0.3
    #   suffix: "Pt"
    #   label: "Calo Jet"
    #   cuts:
    #     - "abs({eta}) < 2.5"
    phase1PuppiJet:
      match_dR: 0.3
      suffix: "Pt"
      label: "Histogrammed PuppiJet"
      cuts:
        - "abs({eta}) < 2.4"
    seededConePuppiJet:
      match_dR: 0.35
      suffix: "Pt"
      label: "Seeded Cone PuppiJet"
      cuts:
        - "abs({eta}) < 2.4"
    trackerJet:
      match_dR: 0.4
      suffix: "Pt"
      label: "Tracker Jet"
      cuts:
        - "abs({eta}) < 2.4"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (barrel)"
  binning:
    min: 0
    max: 500
    step: 10

JetMatchingEndcap:
  sample: TT
  default_version: V30
  reference_object:
    object: "jet"
    suffix: "Pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({eta}) > 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    # caloJet:
    #   match_dR: 0.3
    #   suffix: "Pt"
    #   label: "Calo Jet"
    #   cuts:
    #     - "abs({eta}) < 5"
    phase1PuppiJet:
      match_dR: 0.3
      suffix: "Pt"
      label: "Histogrammed PuppiJet"
      cuts:
        - "abs({eta}) < 2.4"
    seededConePuppiJet:
      match_dR: 0.35
      suffix: "Pt"
      label: "Seeded Cone PuppiJet"
      cuts:
        - "abs({eta}) < 2.4"
    trackerJet:
      match_dR: 0.4
      suffix: "Pt"
      label: "Tracker Jet"
      cuts:
        - "abs({eta}) < 2.4"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (endcap)"
  binning:
    min: 0
    max: 500
    step: 10

JetMatchingForward:
  sample: TT
  default_version: V30
  reference_object:
    object: "jet"
    suffix: "Pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({eta}) > 2.4"
      object:
        - "abs({eta}) < 5"
  test_objects:
    # caloJet:
    #   match_dR: 0.3
    #   suffix: "Pt"
    #   label: "Calo Jet"
    #   cuts:
    #     - "abs({eta}) < 5"
    phase1PuppiJet:
      match_dR: 0.3
      suffix: "Pt"
      label: "Histogrammed PuppiJet"
      cuts:
        - "abs({eta}) < 5"
    seededConePuppiJet:
      match_dR: 0.35
      suffix: "Pt"
      label: "Seeded Cone PuppiJet"
      cuts:
        - "abs({eta}) < 5"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (forward)"
  binning:
    min: 0
    max: 500
    step: 10

