V35nano_ModTT:
  DYLL_M50:
    ntuple_path: /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/emyr/2024Reviews/TTFix_25Mar/dy_TTfix.root
    trees_branches:
      Events:
        GenPart: "all"
        L1gmtTkMuon: "all"
        L1gmtMuon: "all"
        L1tkElectron: "all"
        L1EGbarrel: "all"
        L1EGendcap: "all"
  H2LLP4MuCTau900:
    ntuple_path: /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/emyr/2024Reviews/TTFix_25Mar/h2llp4mu_ctau900_TTfix.root
    trees_branches:
      Events:
        GenPart: "all"
        L1gmtTkMuon: "all"
        L1gmtMuon: "all"
        L1gmtDispMuon: "all"
  H2LLP4MuCTau10000:
    ntuple_path: /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/emyr/2024Reviews/TTFix_25Mar/h2llp4mu_ctau10000_TTfix.root
    trees_branches:
      Events:
        GenPart: "all"
        L1gmtTkMuon: "all"
        L1gmtMuon: "all"
        L1gmtDispMuon: "all"
  Hgg:
    ntuple_path: /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/emyr/2024Reviews/TTFix_25Mar/hgg_TTfix.root
    trees_branches:
      Events:
        GenPart: [pt, eta, phi, pdgId, statusFlags]
        L1tkPhoton: "all" 
        # L1tkElectron: "all" 
        L1EGbarrel: "all" 
        L1EGendcap: "all" 
  VBFHToTauTau:
    ntuple_path: /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/emyr/2024Reviews/TTFix_25Mar/vbfHTauTau_TTfix.root
    trees_branches:
      Events:
        GenVisTau: "all" 
        L1nnPuppiTau: "all" 
        L1hpsTau: "all" 
        L1caloTau: "all" 
        L1nnCaloTau: "all"
  TT:
    ntuple_path: /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/emyr/2024Reviews/TTFix_25Mar/ttbar_TTfix.root
    trees_branches:
      Events:
        # gen
        GenJet: [pt, eta, phi, partonFlavour]
        GenJetAK8: [pt, eta, phi]
        GenMET: "all"
        # sums
        L1puppiMET: [pt, phi]
        L1puppiMLMET: [pt]
        L1puppiJetSC4sums: [pt, phi]
        L1puppiHistoJetSums: [pt, phi]
        # jets
        L1puppiJetSC4: [pt, eta, phi]
        L1puppiJetSC8: [pt, eta, phi]
        L1puppiExtJetSC4: [pt, eta, phi, btagScore]
        L1puppiJetHisto: [pt, eta, phi]
        L1caloJet: [pt, eta, phi]
        L1TrackMET: [pt]
        L1TrackHT: [ht, mht]
        L1TrackJet: [pt, eta, phi]
  MinBias:
    ntuple_path: /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/emyr/2024Reviews/TTFix_25Mar/minbias_TTfix.root
    trees_branches:
      Events:
        ## PV
        L1PV: [z0]
        ## EG
        L1tkPhoton: "all" 
        L1tkElectron: "all" 
        L1EGbarrel: "all" 
        L1EGendcap: "all" 
        ## MUONS
        L1gmtTkMuon: "all" 
        L1gmtMuon: "all"  # aka gmtMuon
        L1gmtDispMuon: "all"  # aka gmtMuon
        ## TAUS
        L1nnPuppiTau: "all" 
        L1hpsTau: "all" 
        L1caloTau: "all" 
        L1nnCaloTau: "all"
        ## MET/Sums
        L1puppiMET: [pt, phi]
        L1puppiMLMET: [pt]
        L1puppiJetSC4sums: [pt, phi]
        L1puppiHistoJetSums: [pt, phi]
        # jets
        L1puppiJetSC4: [pt, eta, phi]
        L1puppiJetSC8: [pt, eta, phi]
        L1puppiExtJetSC4: [pt, eta, phi, btagScore]
        L1puppiJetHisto: [pt, eta, phi]
        L1caloJet: [pt, eta, phi]
        ## track-only
        L1TrackMET: [pt]
        L1TrackHT: [ht, mht]
        L1TrackJet: [pt, eta, phi]
        L1ExtTrackJet: "all"