V31:
  DYLL_M50:
    ntuple_path: /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/alobanov/phase2/menu/ntuples/13X/v29/DYToLL_M-50_TuneCP5_14TeV-pythia8/DY_M50_1252_200PU_v29_13x_fixTkPhi/230822_121429/0000/L*.root
    trees_branches:
      genTree/L1GenTree:
        part_mu: [Id, Stat, Pt, Eta, Phi]
        part_e: [Id, Stat, Pt, Eta, Phi]
      l1PhaseIITree/L1PhaseIITree:
        tkElectron: [Pt, Et, Eta, Phi, Chg, Bx, TrkIso, PfIso, PuppiIso, zVtx, HwQual, EGRefPt, EGRefEta, EGRefPhi, HGC, PassesEleID, PassesPhoID]
        EG: [Pt, Et, Eta, Phi, Bx, Iso, HwQual, HGC, PassesEleID, PassesSaID]
        gmtMuon: [Pt, Eta, Phi, Z0, D0, IPt, IEta, IPhi, IZ0, ID0, Chg, Iso, Qual, Beta, Bx]
        gmtTkMuon: [Pt, Eta, Phi, Z0, D0, IPt, IEta, IPhi, IZ0, ID0, Chg, Iso, Qual, Beta, NStubs, Bx]
        z0L1TkPV: "all"
  TT:
    ntuple_path: /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/alobanov/phase2/menu/ntuples/13X/v29/TT_TuneCP5_14TeV-powheg-pythia8/TT_131_200PU_v29_13x_fixTkPhi/230822_122619/0000/L*.root
    trees_branches:
      genTree/L1GenTree:
        genMetTrue: "all"
        jet: "all"
      l1PhaseIITree/L1PhaseIITree:
        puppiMET: "all"
        phase1PuppiJet: "all"
        phase1PuppiMHT: "all"
        phase1PuppiHT: "all"
        seededConePuppiJet: [Pt, Et, Eta, Phi]
        seededConeExtendedPuppiJet: [Pt, Et, Eta, Phi, BJetNN]
        seededConePuppiHT: "all"
        seededConePuppiMHT: "all"
        trackerJet: [Pt, Eta, Phi]
        trackerMET: "all"
        trackerMHT: "all"
        trackerHT: "all"
        # caloJet: "all"
        caloJet: [Et, Pt, Eta, Phi]
        ## DEBUG
        #tkElectron: [Pt, Et, Eta, Phi, Chg, Bx, TrkIso, PfIso, PuppiIso, zVtx, HwQual, EGRefPt, EGRefEta, EGRefPhi, HGC, PassesEleID, PassesPhoID]
        #tkPhoton: [Pt, Et, Eta, Phi, Bx, TrkIso, HwQual, HGC, PassesEleID, PassesPhoID]
        z0L1TkPV: "all"
  VBFHToTauTau:
    ntuple_path: /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/alobanov/phase2/menu/ntuples/13X/v29/VBFHToTauTau_M-125_TuneCP5_14TeV-powheg-pythia8/VBFHToTauTau_131_200PU_v29_13x_fixTkPhi/230822_122634/0000/L*.root
    trees_branches:
      genTree/L1GenTree:
        part_tau: [Id, Stat, Pt, Eta, Phi, Parent, E]
      l1PhaseIITree/L1PhaseIITree:
        nnTau: [Et, Eta, Pt, Phi, FullIso, Z0, PassTightNN, Chg, DXY, PassLooseNN]
        caloTau: [Et, Eta, Pt, Phi, Iso, HwQual, Bx]
  HHToTauTau:
    ntuple_path: /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/alobanov/phase2/menu/ntuples/13X/v29/GluGluToHHTo2B2Tau_node_SM_TuneCP5_14TeV-madgraph-pythia8/HHTo2B2Tau_131_200PU_v29_13x_fixTkPhi/230824_130354/0000/L*.root
    trees_branches:
      genTree/L1GenTree:
        part_tau: [Id, Stat, Pt, Eta, Phi, Parent, E]
      l1PhaseIITree/L1PhaseIITree:
        nnTau: [Et, Eta, Pt, Phi, FullIso, Z0, PassTightNN, Chg, DXY, PassLooseNN]
        caloTau: [Et, Eta, Pt, Phi, Iso, HwQual]
  Hgg:
    ntuple_path: /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/alobanov/phase2/menu/ntuples/13X/v29/GluGluHToGG_M-125_TuneCP5_14TeV-powheg-pythia8/GluGluHToGG_131_200PU_v29_13x_fixTkPhi/230822_122650/0000/L*.root
    trees_branches:
      genTree/L1GenTree:
        part_gamma: [Id, Stat, Pt, Eta, Phi]
      l1PhaseIITree/L1PhaseIITree:
        tkPhoton: [Pt, Et, Eta, Phi, Bx, TrkIso, HwQual, HGC, PassesEleID, PassesPhoID, TrkIsoPV]
        EG: [Pt, Et, Eta, Phi, Bx, Iso, HwQual, HGC, PassesEleID, PassesSaID]
  MinBias:
    ntuple_path: /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/alobanov/phase2/menu/ntuples/13X/v29/MinBias_TuneCP5_14TeV-pythia8/MinBias_131_v29_13x_fixTkPhi/230825_103803/M*.root
    trees_branches:
      l1PhaseIITree/L1PhaseIITree:
        puppiMET: "all"
        phase1PuppiJet: "all"
        phase1PuppiMHT: "all"
        phase1PuppiHT: "all"
        seededConePuppiJet: [Pt, Et, Eta, Phi]
        seededConeExtendedPuppiJet: [Pt, Et, Eta, Phi, BJetNN]
        seededConeExtendedPuppiHT: "all"
        seededConePuppiHT: "all"
        seededConePuppiMHT: "all"
        caloJet: [Et, Pt, Eta, Phi]
        tkElectron: [Pt, Et, Eta, Phi, Chg, TrkIso, PfIso, PuppiIso, zVtx, HwQual, HGC, PassesEleID, PassesPhoID]
        EG: [Pt, Et, Eta, Phi, Iso, HwQual, HGC, PassesEleID, PassesSaID]
        gmtTkMuon: [Pt, Eta, Phi, Z0, D0, Chg, Qual ]
        gmtMuon: [Pt, Eta, Phi, Z0, D0, Chg, Qual ]
        nnTau: [Et, Eta, Pt, Phi, Z0, PassTightNN, Chg, DXY, PassLooseNN]
        tkPhoton: [Pt, Et, Eta, Phi, TrkIso, HwQual, HGC, PassesEleID, PassesPhoID]
        z0L1TkPV: "all"
        caloTau: [Et, Eta, Pt, Phi, Iso, HwQual]
        trackerJet: [Pt, Eta, Phi]
        trackerMET: "all"
        trackerMHT: "all"
        trackerHT: "all"


