JetDefaultRates:
  sample: MinBias
  version: V33nano
  test_objects:
    - L1puppiJetHisto:default
    - L1puppiJetSC4:default
    - L1caloJet:default
    - L1TrackJet:default
  binning:
    min: 40
    max: 420
    step: 20

JetsByRegion:
  sample: MinBias
  version: V33nano
  test_objects:
    - L1puppiJetSC4:default:barrel
    - L1puppiJetSC4:default:endcap
    - L1caloJet:default:barrel
    - L1caloJet:default:endcap
    - L1TrackJet:default:barrel
    - L1TrackJet:default:endcap
  binning:
    min: 40
    max: 420
    step: 20

JetSC8Rates:
  sample: MinBias
  version: V33nano
  test_objects:
    - L1puppiJetSC4:default
    - L1puppiJetSC8:default
  binning:
    min: 40
    max: 420
    step: 20


JetSC8Rates_byRegion:
  sample: MinBias
  version: V33nano
  test_objects:
    # - L1puppiJetSC4:default
    - L1puppiJetSC8:default
    - L1puppiJetSC8:default:barrel
    - L1puppiJetSC8:default:endcap
  binning:
    min: 40
    max: 420
    step: 20