### SC8 wide cone jet seeds
L1_SinglePfJet8:
  cross_masks: []
  leg1:
    threshold_cut: offline_pt >= 230.0
    obj: L1puppiJetSC8:default
L1_DoublePFJet8_dEtaMax:
  cross_masks:
    - abs(leg2.eta-leg1.eta) < 1.6
  leg1:
    threshold_cut: leg1.offline_pt >= 200.0
    obj: L1puppiJetSC8:default
  leg2:
    threshold_cut: leg2.offline_pt >= 200.0
    obj: L1puppiJetSC8:default
### Bjet seed
L1_PFHTT_QuadJet_BTagNNScore:
  cross_masks:
    - (leg2.btagScore + leg3.btagScore + leg4.btagScore + leg5.btagScore) > 2.20
  leg1:
    threshold_cut: offline_pt >= 299.0
    obj: L1puppiJetSC4sums:HT
  leg2:
    threshold_cut: pt >= 25
    obj: L1puppiExtJetSC4:default
  leg3:
    threshold_cut: pt >= 25
    obj: L1puppiExtJetSC4:default
  leg4:
    threshold_cut: pt >= 25
    obj: L1puppiExtJetSC4:default
  leg5:
    threshold_cut: pt >= 25
    obj: L1puppiExtJetSC4:default
# ##############################
# ### Displaced Muons
# ##############################
L1_SingleDispMu:
  cross_masks: []
  leg1:
    threshold_cut: pt >= 22.0
    obj: L1gmtDispMuon:qual15_Eta2p0
# L1_SingleDispMu_BMTF:
#   cross_masks: []
#   leg1:
#     threshold_cut: pt >= 22.0
#     obj: L1gmtDispMuon:default:barrel
# L1_SingleDispMu_OMTF:
#   cross_masks: []
#   leg1:
#     threshold_cut: pt >= 22.0
#     obj: L1gmtDispMuon:default:overlap
# # L1_SingleDispMu_EMTF:
# #   cross_masks: []
# #   leg1:
# #     threshold_cut: pt >= 22.0
# #     obj: L1gmtDispMuon:default:endcap
# L1_SingleDispMu_EMTF_SQ_eta2p0:
#   cross_masks: []
#   leg1:
#     threshold_cut: pt >= 22.0
#     obj: L1gmtDispMuon:qual15_Eta2p0:endcap
L1_DoubleDispMu:
  cross_masks: []
  leg1:
    threshold_cut: pt > 15.0
    obj: L1gmtDispMuon:default
  leg2:
    threshold_cut: pt > 7
    obj: L1gmtDispMuon:default
# # ##############################
# # ### GTT
# # ##############################
L1_W3pi_GTT:
  cross_masks: []
  leg1:
    threshold_cut: pt > -99
    obj: L1TrackTripletWord:default
# L1_TkDispHT:
#   cross_masks: []
#   leg1:
#     threshold_cut: ht >= 200
#     obj: L1ExtTrackHT:HT


# #### FOR DEBUG
# #### STEP1 muons
# L1_SingleTkMu:
#   cross_masks: []
#   leg1:
#     threshold_cut: offline_pt >= 22.0
#     obj: L1gmtTkMuon:Medium
# L1_TripleTkMu:
#   cross_masks:
#     - abs(leg2.z0-leg1.z0) < 1
#     - abs(leg3.z0-leg1.z0) < 1
#   leg1:
#     threshold_cut: pt > 5
#     obj: L1gmtTkMuon:Medium
#   leg2:
#     threshold_cut: pt > 3
#     obj: L1gmtTkMuon:Medium
#   leg3:
#     threshold_cut: pt > 3
#     obj: L1gmtTkMuon:Medium
# L1_DoubleTkMu:
#   cross_masks:
#     - ((abs(leg1.z0-leg2.z0) < 1) & (leg1.deltaR(leg2) > 0))
#   leg1:
#     threshold_cut: offline_pt > 15.0
#     obj: L1gmtTkMuon:Medium
#   leg2:
#     threshold_cut: pt > 7
#     obj: L1gmtTkMuon:Medium
# L1_DoubleTkMu4_SQ_OS_dR_Max1p2:
#   cross_masks:
#     - ((leg1.deltaR(leg2) < 1.2) & (leg1.deltaR(leg2) > 0))
#     - ((leg1.charge*leg2.charge < 0.0) & (leg1.deltaR(leg2) > 0))
#     - ((abs(leg2.z0-leg1.z0) < 1) & (leg1.deltaR(leg2) > 0))
#   leg1:
#     threshold_cut: pt > 4
#     obj: L1gmtTkMuon:Medium
#   leg2:
#     threshold_cut: pt > 4
#     obj: L1gmtTkMuon:Medium