BJetEff_Pt:
  files:
    JetMatching_Pt_Pt30ToInf_genBJets_-999_V31:
      object: seededConeExtendedPuppiJet
      dir: outputs/V31/turnons/
      label: "Signal: Matched b-jets"
    JetMatching_Pt_Pt30ToInf_genNotBJets_-999_V31:
      object: seededConeExtendedPuppiJet
      dir: outputs/V31/turnons/
      label: "Background: Unmatched b-jets"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency"
  watermark: "BJet_Pt"
  save_dir: "outputs/V31/BJet/turnons"


BJetEff_Eta:
  files:
    JetMatching_Eta_Pt30ToInf_genBJets_-999_V31:
      object: seededConeExtendedPuppiJet
      dir: outputs/V31/turnons/
      label: "Signal: Matched b-jets"
    JetMatching_Eta_Pt30ToInf_genNotBJets_-999_V31:
      object: seededConeExtendedPuppiJet
      dir: outputs/V31/turnons/
      label: "Background: Unmatched b-jets"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency"
  watermark: "BJet_Eta"
  save_dir: "outputs/V31/BJet/turnons"
