Jets_Turnons_V29:
  files:
    JetMatching_25_-999_V29:
      object: seededConePuppiJet
      dir: outputs/V29/turnons/
      label: "SC PuppiJet (L1 $p_T$>25)"
    JetMatching_50_-999_V29:
      object: seededConePuppiJet
      dir: outputs/V29/turnons/
      label: "SC PuppiJet (L1 $p_T$>50)"
    JetMatching_75_-999_V29:
      object: seededConePuppiJet
      dir: outputs/V29/turnons/
      label: "SC PuppiJet (L1 $p_T$>75)"
    JetMatching_100_-999_V29:
      object: seededConePuppiJet
      dir: outputs/V29/turnons/
      label: "SC PuppiJet (L1 $p_T$>100)"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Efficiency"
  watermark: "V29_SCJet_Comp"
  save_dir: "outputs/V29/turnons"
