Photons_Turnons_V29:
  files:
    PhotonsTrigger_Iso_Inclusive_10_V29:
      object: tkIsoPhoton
      dir: outputs/V29/turnons/
      label: "tkIsoPhoton (L1 $p_T$>10)"
    PhotonsTrigger_Iso_Inclusive_20_V29:
      object: tkIsoPhoton
      dir: outputs/V29/turnons/
      label: "tkIsoPhoton (L1 $p_T$>20)"
    PhotonsTrigger_Iso_Inclusive_30_V29:
      object: tkIsoPhoton
      dir: outputs/V29/turnons/
      label: "tkIsoPhoton (L1 $p_T$>30)"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Trigger Efficiency"
  watermark: "V29_tkIsoPhoton_Comp"
  save_dir: "outputs/V29/turnons"
