Jets_Turnons_V29:
  files:
    JetTurnon_SC_Inclusive_25_V29:
      object: seededConePuppiJet
      dir: outputs/V29/turnons/
      label: "SC PuppiJet (L1 $p_T$>25)"
    JetTurnon_SC_Inclusive_50_V29:
      object: seededConePuppiJet
      dir: outputs/V29/turnons/
      label: "SC PuppiJet (L1 $p_T$>50)"
    JetTurnon_SC_Inclusive_75_V29:
      object: seededConePuppiJet
      dir: outputs/V29/turnons/
      label: "SC PuppiJet (L1 $p_T$>75)"
    JetTurnon_SC_Inclusive_100_V29:
      object: seededConePuppiJet
      dir: outputs/V29/turnons/
      label: "SC PuppiJet (L1 $p_T$>100)"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Trigger Efficiency"
  watermark: "V29_SCJet_Comp"
  save_dir: "outputs/V29/turnons"
