ElectronsMatching_25:
  sample: DYLL_M50
  default_version: V29
  reference_object:
    object: "part_e"
    suffix: "Pt"
    label: "Gen Electrons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "{pt} > 25"
      object:
        - "abs({eta}) < 2.5"
  test_objects:
    EG:
      suffix: "Pt"
      label: "EG"
      match_dR: 0.2
      quality_id: "QUAL_125x_EGID"
      cuts:
        - "abs({eta}) < 2.5"
    tkElectron:
      suffix: "Pt"
      label: "TkElectron"
      match_dR: 0.15
      cuts:
        - "abs({eta}) < 2.5"
        - "{passeseleid} == 1"
    tkIsoElectron:
      base_obj: "tkElectron"
      suffix: "Pt"
      label: "TkIsoElectron"
      iso_BB: 0.13
      iso_EE: 0.28
      iso_branch: "trkiso"
      match_dR: 0.15
      cuts:
        - "{passeseleid} == 1"
        - "abs({eta}) < 2.5"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency"
  binning:
    min: 0
    max: 150
    step: 3
