Electrons_Turnons_V29:
  files:
    ElectronsTrigger_Iso_Inclusive_10_V29:
      object: tkIsoElectron
      dir: outputs/V29/turnons/
      label: "tkIsoElectron (L1 $p_T$>10)"
    ElectronsTrigger_Iso_Inclusive_20_V29:
      object: tkIsoElectron
      dir: outputs/V29/turnons/
      label: "tkIsoElectron (L1 $p_T$>20)"
    ElectronsTrigger_Iso_Inclusive_30_V29:
      object: tkIsoElectron
      dir: outputs/V29/turnons/
      label: "tkIsoElectron (L1 $p_T$>30)"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Trigger Efficiency"
  watermark: "V29_tkIsoEle_Comp"
  save_dir: "outputs/V29/turnons"
