ElectronsMatching_10:
  sample: DYLL_M50
  default_version: V29
  reference_object:
    object: "part_e"
    suffix: "Pt"
    label: "Gen Electrons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
      object:
        - "abs({eta}) < 2.5"
  test_objects:
    EG:
      suffix: "Pt"
      label: "EG (L1 $p_{T}$ > 10 GeV)"
      match_dR: 0.2
      quality_id: "QUAL_125x_EGID"
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 10"
    tkElectron:
      suffix: "Pt"
      label: "TkElectron (L1 $p_{T}$ > 10 GeV)"
      match_dR: 0.15
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 10"
        - "{passeseleid} == 1"
    tkIsoElectron:
      base_obj: "tkElectron"
      suffix: "Pt"
      label: "TkIsoElectron (L1 $p_{T}$ > 10 GeV)"
      iso_BB: 0.13
      iso_EE: 0.28
      iso_branch: "trkiso"
      match_dR: 0.15
      cuts:
        - "abs({eta}) < 2.5"
        - "{passeseleid} == 1"
        - "{pt} > 10"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Efficiency"
  binning:
    min: 0
    max: 150
    step: 3

ElectronsMatching_20:
  sample: DYLL_M50
  default_version: V29
  reference_object:
    object: "part_e"
    suffix: "Pt"
    label: "Gen Electrons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
      object:
        - "abs({eta}) < 2.5"
  test_objects:
    EG:
      suffix: "Pt"
      label: "EG (L1 $p_{T}$ > 20 GeV)"
      match_dR: 0.2
      quality_id: "QUAL_125x_EGID"
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 20"
    tkElectron:
      suffix: "Pt"
      label: "TkElectron (L1 $p_{T}$ > 20 GeV)"
      match_dR: 0.15
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 20"
        - "{passeseleid} == 1"
    tkIsoElectron:
      base_obj: "tkElectron"
      suffix: "Pt"
      label: "TkIsoElectron (L1 $p_{T}$ > 20 GeV)"
      iso_BB: 0.13
      iso_EE: 0.28
      iso_branch: "trkiso"
      match_dR: 0.15
      cuts:
        - "abs({eta}) < 2.5"
        - "{passeseleid} == 1"
        - "{pt} > 20"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Efficiency"
  binning:
    min: 0
    max: 150
    step: 3

ElectronsMatching_25:
  sample: DYLL_M50
  default_version: V29
  reference_object:
    object: "part_e"
    suffix: "Pt"
    label: "Gen Electrons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
      object:
        - "abs({eta}) < 2.5"
  test_objects:
    EG:
      suffix: "Pt"
      label: "EG (L1 $p_{T}$ > 25 GeV)"
      match_dR: 0.2
      quality_id: "QUAL_125x_EGID"
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 25"
    tkElectron:
      suffix: "Pt"
      label: "TkElectron (L1 $p_{T}$ > 25 GeV)"
      match_dR: 0.15
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 25"
        - "{passeseleid} == 1"
    tkIsoElectron:
      base_obj: "tkElectron"
      suffix: "Pt"
      label: "TkIsoElectron (L1 $p_{T}$ > 25 GeV)"
      iso_BB: 0.13
      iso_EE: 0.28
      iso_branch: "trkiso"
      match_dR: 0.15
      cuts:
        - "abs({eta}) < 2.5"
        - "{passeseleid} == 1"
        - "{pt} > 25"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Efficiency"
  binning:
    min: 0
    max: 150
    step: 3

ElectronsMatching_30:
  sample: DYLL_M50
  default_version: V29
  reference_object:
    object: "part_e"
    suffix: "Pt"
    label: "Gen Electrons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
      object:
        - "abs({eta}) < 2.5"
  test_objects:
    EG:
      suffix: "Pt"
      label: "EG (L1 $p_{T}$ > 30 GeV)"
      match_dR: 0.2
      quality_id: "QUAL_125x_EGID"
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 30"
    tkElectron:
      suffix: "Pt"
      label: "TkElectron (L1 $p_{T}$ > 30 GeV)"
      match_dR: 0.15
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 30"
        - "{passeseleid} == 1"
    tkIsoElectron:
      base_obj: "tkElectron"
      suffix: "Pt"
      label: "TkIsoElectron (L1 $p_{T}$ > 30 GeV)"
      iso_BB: 0.13
      iso_EE: 0.28
      iso_branch: "trkiso"
      match_dR: 0.15
      cuts:
        - "abs({eta}) < 2.5"
        - "{passeseleid} == 1"
        - "{pt} > 30"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Efficiency"
  binning:
    min: 0
    max: 150
    step: 3
