JetMatching_25:
  sample: TT
  default_version: V29
  reference_object:
    object: "jet"
    suffix: "Pt"
    label: "Gen Jets"
    cuts:
      object:
        - "abs({eta}) < 2.5"
  test_objects:
    seededConePuppiJet:
      match_dR: 0.35
      suffix: "Pt"
      label: "Seeded Cone PuppiJet (L1 $p_{T}$ > 25 GeV)"
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 25"
    trackerJet:
      match_dR: 0.4
      suffix: "Pt"
      label: "Tracker Jet (L1 $p_{T}$ > 25 GeV)"
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 25"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Efficiency"
  binning:
    min: 0
    max: 500
    step: 10

JetMatching_50:
  sample: TT
  default_version: V29
  reference_object:
    object: "jet"
    suffix: "Pt"
    label: "Gen Jets"
    cuts:
      object:
        - "abs({eta}) < 2.5"
  test_objects:
    seededConePuppiJet:
      match_dR: 0.35
      suffix: "Pt"
      label: "Seeded Cone PuppiJet (L1 $p_{T}$ > 50 GeV)"
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 50"
    trackerJet:
      match_dR: 0.4
      suffix: "Pt"
      label: "Tracker Jet (L1 $p_{T}$ > 50 GeV)"
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 50"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Efficiency"
  binning:
    min: 0
    max: 500
    step: 10

JetMatching_75:
  sample: TT
  default_version: V29
  reference_object:
    object: "jet"
    suffix: "Pt"
    label: "Gen Jets"
    cuts:
      object:
        - "abs({eta}) < 2.5"
  test_objects:
    seededConePuppiJet:
      match_dR: 0.35
      suffix: "Pt"
      label: "Seeded Cone PuppiJet (L1 $p_{T}$ > 75 GeV)"
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 75"
    trackerJet:
      match_dR: 0.4
      suffix: "Pt"
      label: "Tracker Jet (L1 $p_{T}$ > 75 GeV)"
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 75"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Efficiency"
  binning:
    min: 0
    max: 500
    step: 10

JetMatching_160:
  sample: TT
  default_version: V29
  reference_object:
    object: "jet"
    suffix: "Pt"
    label: "Gen Jets"
    cuts:
      object:
        - "abs({eta}) < 2.5"
  test_objects:
    seededConePuppiJet:
      match_dR: 0.35
      suffix: "Pt"
      label: "Seeded Cone PuppiJet (L1 $p_{T}$ > 160 GeV)"
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 160"
    trackerJet:
      match_dR: 0.4
      suffix: "Pt"
      label: "Tracker Jet (L1 $p_{T}$ > 160 GeV)"
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 160"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Efficiency"
  binning:
    min: 0
    max: 500
    step: 10

