JetTurnon_Inclusive:
  sample: TT
  default_version: V29
  reference_object:
    object: "jet"
    suffix: "Pt"
    label: "Gen Jets"
  test_objects:
    phase1PuppiJet:
      match_dR: 0.3
      suffix: "Pt"
      label: "Histogrammed PuppiJet"
    seededConePuppiJet:
      match_dR: 0.35
      suffix: "Pt"
      label: "Seeded Cone PuppiJet"
    trackerJet:
      match_dR: 0.4
      suffix: "Pt"
      label: "Tracker Jet"
  thresholds: [100]
  scalings:
    method: "naive"
    threshold: 0.95
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV, barrel)"
  binning:
    min: 0
    max: 500
    step: 10
