JetMatching_Eta_Pt40To100:
  sample: TT
  default_version: V29
  reference_object: 
    object: "jet"
    suffix: "Eta"
    label: "Gen Jets"
    cuts:
      event:
        - "{pt} > 40"
        - "{pt} < 100"
      object:
        - "abs({eta}) < 5"
  test_objects:
    seededConePuppiJet:
      match_dR: 0.35
      suffix: "Eta"
      label: "Seeded Cone PuppiJet"
      cuts:
        - "abs({eta}) < 5"
    trackerJet:
      match_dR: 0.4
      suffix: "Eta"
      label: "Tracker Jet"
      cuts:
        - "abs({eta}) < 2.4"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (40-100 GeV)"
  binning:
    min: -5
    max: 5
    step: 0.25

JetMatching_Eta_Pt100ToInf:
  sample: TT
  default_version: V29
  reference_object: 
    object: "jet"
    suffix: "Eta"
    label: "Gen Jets"
    cuts:
      event:
        - "{pt} > 100"
      object:
        - "abs({eta}) < 5"
  test_objects:
    seededConePuppiJet:
      match_dR: 0.35
      suffix: "Eta"
      label: "Seeded Cone PuppiJet"
      cuts:
       - "abs({eta}) < 5"
    trackerJet:
      match_dR: 0.4
      suffix: "Eta"
      label: "Tracker Jet"
      cuts:
        - "abs({eta}) < 2.4"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (>100 GeV)"
  binning:
    min: -5
    max: 5
    step: 0.25
