MET:
  sample: TT
  default_version: V29
  reference_object:
    object: "genMetTrue"
    suffix: ""
    label: "Gen MET"
  test_objects:
    puppiMET:
      suffix: "et"
      label: "Puppi MET"
    trackerMET:
      suffix: ""
      label: "Tracker MET"
  thresholds: [90]
  xlabel: "Gen. MET (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV)"
  scalings:
    method: "naive"
    threshold: 0.90
  binning:
    min: 0
    max: 500
    step: 20

MHT30:
  sample: TT
  default_version: V29
  reference_object:
    object: "jet"
    suffix: "Pt"
    label: "Gen MHT"
    cuts:
      object:
        - "abs({eta}) < 2.4"
        - "{pt} > 30"
    trafo: "MHT"
  test_objects:
    seededConePuppiMHT:
      suffix: "et"
      label: "SeededCone MHT"
    trackerMHT:
      suffix: ""
      label: "Tracker MHT"
  thresholds: [150]
  scalings:
    method: "naive"
    threshold: 0.90
  xlabel: "Gen. MHT30 (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV)"
  binning:
    min: 0
    max: 500
    step: 20

HT:
  sample: TT
  default_version: V29
  reference_object:
    object: "jet"
    suffix: "Pt"
    label: "Gen HT"
    trafo: "HT"
    cuts:
       object:
         - "abs({eta}) < 2.4"
         - "{pt} > 30"
  test_objects:
    seededConePuppiHT:
      suffix: ""
      label: "SeededCone HT"
    trackerHT:
      suffix: ""
      label: "Tracker HT"
  thresholds: [350]
  scalings:
    method: "naive"
    threshold: 0.90
  xlabel: "Gen. HT (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV)"
  binning:
    min: 0
    max: 750
    step: 20
