PhotonsMatching_25:
  sample: Hgg
  default_version: V29
  reference_object:
    object: "part_gamma"
    suffix: "Pt"
    label: "Gen Photons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
      object:
        - "abs({eta}) < 2.5"
  test_objects:
    EG:
      suffix: "Pt"
      label: "EG"
      match_dR: 0.2
      quality_id: "QUAL_125x_EGID"
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 25"
    tkPhoton:
      match_dR: 0.15
      suffix: "Pt"
      label: "tkPhoton"
      quality_id: "QUAL_125x_tkPhoID"
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 25"
    tkIsoPhoton:
      base_obj: "tkPhoton"
      match_dR: 0.15
      suffix: "Pt"
      label: "tkIsoPhoton"
      iso_EE: 0.2
      iso_BB: 0.2
      iso_branch: trkiso
      quality_id: "QUAL_125x_tkPhoID"
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 25"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency"
  binning:
    min: 0
    max: 100
    step: 3
