PhotonsMatching_10:
  sample: Hgg
  default_version: V29
  reference_object:
    object: "part_gamma"
    suffix: "Pt"
    label: "Gen Photons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
      object:
        - "abs({eta}) < 2.5"
  test_objects:
    EG:
      suffix: "Pt"
      label: "EG (L1 $p_{T}$ > 10 GeV)"
      match_dR: 0.2
      quality_id: "QUAL_125x_EGID"
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 10"
    tkPhoton:
      match_dR: 0.15
      suffix: "Pt"
      label: "tkPhoton (L1 $p_{T}$ > 10 GeV)"
      quality_id: "QUAL_125x_tkPhoID"
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 10"
    tkIsoPhoton:
      base_obj: "tkPhoton"
      match_dR: 0.15
      suffix: "Pt"
      label: "tkIsoPhoton (L1 $p_{T}$ > 10 GeV)"
      iso_EE: 0.2
      iso_BB: 0.2
      iso_branch: trkiso
      quality_id: "QUAL_125x_tkPhoID"
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 10"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Efficiency"
  binning:
    min: 0
    max: 100
    step: 3

PhotonsMatching_20:
  sample: Hgg
  default_version: V29
  reference_object:
    object: "part_gamma"
    suffix: "Pt"
    label: "Gen Photons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
      object:
        - "abs({eta}) < 2.5"
  test_objects:
    EG:
      suffix: "Pt"
      label: "EG (L1 $p_{T}$ > 20 GeV)"
      match_dR: 0.2
      quality_id: "QUAL_125x_EGID"
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 20"
    tkPhoton:
      match_dR: 0.15
      suffix: "Pt"
      label: "tkPhoton (L1 $p_{T}$ > 20 GeV)"
      quality_id: "QUAL_125x_tkPhoID"
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 20"
    tkIsoPhoton:
      base_obj: "tkPhoton"
      match_dR: 0.15
      suffix: "Pt"
      label: "tkIsoPhoton (L1 $p_{T}$ > 20 GeV)"
      iso_EE: 0.2
      iso_BB: 0.2
      iso_branch: trkiso
      quality_id: "QUAL_125x_tkPhoID"
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 20"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Efficiency"
  binning:
    min: 0
    max: 100
    step: 3

PhotonsMatching_25:
  sample: Hgg
  default_version: V29
  reference_object:
    object: "part_gamma"
    suffix: "Pt"
    label: "Gen Photons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
      object:
        - "abs({eta}) < 2.5"
  test_objects:
    EG:
      suffix: "Pt"
      label: "EG (L1 $p_{T}$ > 25 GeV)"
      match_dR: 0.2
      quality_id: "QUAL_125x_EGID"
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 25"
    tkPhoton:
      match_dR: 0.15
      suffix: "Pt"
      label: "tkPhoton (L1 $p_{T}$ > 25 GeV)"
      quality_id: "QUAL_125x_tkPhoID"
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 25"
    tkIsoPhoton:
      base_obj: "tkPhoton"
      match_dR: 0.15
      suffix: "Pt"
      label: "tkIsoPhoton (L1 $p_{T}$ > 25 GeV)"
      iso_EE: 0.2
      iso_BB: 0.2
      iso_branch: trkiso
      quality_id: "QUAL_125x_tkPhoID"
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 25"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Efficiency"
  binning:
    min: 0
    max: 100
    step: 3

PhotonsMatching_30:
  sample: Hgg
  default_version: V29
  reference_object:
    object: "part_gamma"
    suffix: "Pt"
    label: "Gen Photons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
      object:
        - "abs({eta}) < 2.5"
  test_objects:
    EG:
      suffix: "Pt"
      label: "EG (L1 $p_{T}$ > 30 GeV)"
      match_dR: 0.2
      quality_id: "QUAL_125x_EGID"
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 30"
    tkPhoton:
      match_dR: 0.15
      suffix: "Pt"
      label: "tkPhoton (L1 $p_{T}$ > 30 GeV)"
      quality_id: "QUAL_125x_tkPhoID"
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 30"
    tkIsoPhoton:
      base_obj: "tkPhoton"
      match_dR: 0.15
      suffix: "Pt"
      label: "tkIsoPhoton (L1 $p_{T}$ > 30 GeV)"
      iso_EE: 0.2
      iso_BB: 0.2
      iso_branch: trkiso
      quality_id: "QUAL_125x_tkPhoID"
      cuts:
        - "abs({eta}) < 2.5"
        - "{pt} > 30"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Efficiency"
  binning:
    min: 0
    max: 100
    step: 3
