TauMatching_Eta_Pt10to25:
  sample: VBFHToTauTau
  default_version: V29
  reference_object:
    object: "part_tau"
    suffix: "Eta"
    label: "Gen Taus"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "{pt} < 10"
        - "{pt} > 25"
      object:
        - "abs({eta}) < 2.5"
  test_objects:
    nnTau:
      suffix: "Eta"
      label: "NN Tau"
      cuts:
        - "abs({eta}) < 2.5"
        - "{passloosenn}==1"
      match_dR: 0.1
    caloTau:
      suffix: "Eta"
      label: "Calo Tau"
      cuts:
        - "abs({eta}) < 2.5"
      match_dR: 0.3
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency ($10 < p_T < 25$ GeV)"
  binning:
    min: -3
    max: 3
    step: 0.2

TausMatching_Eta_Pt25toInf:
  sample: VBFHToTauTau
  default_version: V29
  reference_object:
    object: "part_tau"
    suffix: "Eta"
    label: "Gen Taus"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "{pt} > 25"
      object:
        - "abs({eta}) < 2.5"
  test_objects:
    nnTau:
      suffix: "Eta"
      label: "NN Tau"
      cuts:
        - "abs({eta}) < 2.5"
        - "{passloosenn}==1"
      match_dR: 0.1
    caloTau:
      suffix: "Eta"
      label: "Calo Tau"
      cuts:
        - "abs({eta}) < 2.5"
      match_dR: 0.3
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency ($p_T > 25$ GeV)"
  binning:
    min: -3
    max: 3
    step: 0.2

TauMatching_Eta_Pt40to100:
  sample: VBFHToTauTau
  default_version: V29
  reference_object:
    object: "part_tau"
    suffix: "Eta"
    label: "Gen Taus"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "{pt} < 100"
        - "{pt} > 40"
      object:
        - "abs({eta}) < 2.5"
  test_objects:
    nnTau:
      suffix: "Eta"
      label: "NN Tau"
      cuts:
        - "abs({eta}) < 2.5"
        - "{passloosenn}==1"
      match_dR: 0.1
    caloTau:
      suffix: "Eta"
      label: "Calo Tau"
      cuts:
        - "abs({eta}) < 2.5"
      match_dR: 0.3
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency ($40 < p_T < 100$ GeV)"
  binning:
    min: -3
    max: 3
    step: 0.2

TausMatching_Eta_Pt100toInf:
  sample: VBFHToTauTau
  default_version: V29
  reference_object:
    object: "part_tau"
    suffix: "Eta"
    label: "Gen Taus"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "{pt} > 100"
      object:
        - "abs({eta}) < 2.5"
  test_objects:
    nnTau:
      suffix: "Eta"
      label: "NN Tau"
      cuts:
        - "abs({eta}) < 2.5"
        - "{passloosenn}==1"
      match_dR: 0.1
    caloTau:
      suffix: "Eta"
      label: "Calo Tau"
      cuts:
        - "abs({eta}) < 2.5"
      match_dR: 0.3
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency ($p_T > 100$ GeV)"
  binning:
    min: -3
    max: 3
    step: 0.2
