TauTrigger_Inclusive:
  sample: VBFHToTauTau
  default_version: V29
  reference_object:
    object: "part_tau"
    suffix: "Pt"
    label: "Gen Taus"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
  test_objects:
    nnTau:
      suffix: "Pt"
      label: "NN Tau"
      cuts:
        - "{passloosenn}==1"
      match_dR: 0.1
    caloTau:
      suffix: "Pt"
      label: "Calo Tau"
      match_dR: 0.3
  xlabel: "Gen. pT (GeV)"
  ylabel: "Trigger Efficiency (L1 $p_T > <threshold>$ GeV)"
  thresholds: [25]
  scalings:
    method: "naive"
    threshold: 0.90
  binning:
    min: 0
    max: 150
    step: 6
