caloJet:
  match_dR: 0.3
  label: "Calo Jet"
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.5]
    endcap: [1.5, 2.4]
    forward: [2.4, 5]
  cuts:
    inclusive:
      - "abs({eta}) < 7"
  ids:
    default:
      cuts:
        inclusive:
          - "abs({eta}) < 7"
    PtGr30:
      label: "CaloJet, pt > 30"
      cuts:
        inclusive:
          - "abs({eta}) < 7"
          - "{pt} > 30"

seededConeExtendedPuppiJet:
  match_dR: 0.35
  label: "Seeded Cone Extended PuppiJet"
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.5]
    endcap: [1.5, 2.4]
    forward: [2.4, 5]
  ids:
    default:
      cuts:
        inclusive:
          - "abs({eta}) < 5"
    bjetnn:
      cuts:
        inclusive:
          - "abs({eta}) < 2.4"
          - "{bjetnn} > 0.71"

phase1PuppiJet:
  match_dR: 0.3
  label: "Histogrammed PuppiJet"
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.5]
    endcap: [1.5, 2.4]
    forward: [2.4, 5]
  ids:
    default:
      cuts:
        inclusive:
          - "abs({eta}) < 7"

seededConePuppiJet:
  match_dR: 0.35
  label: "Seeded Cone PuppiJet"
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.5]
    endcap: [1.5, 2.4]
    forward: [2.4, 5]
  ids:
    default:
      cuts:
        inclusive:
          - "abs({eta}) < 7"

trackerJet:
  match_dR: 0.4
  label: "Tracker Jet"
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.5]
    endcap: [1.5, 2.4]
  ids:
    default:
      cuts:
        inclusive:
          - "abs({eta}) < 7"
