phase1PuppiHT:
  label: "Histogrammed Puppi HT"
  ids:
    default: {}

phase1PuppiMHT:
  label: "Phase1 Puppi MHT"
  ids:
    default: {}

puppiMET:
  label: "Puppi MET"
  ids:
    default: {}

seededConePuppiHT:
  label: "SeededCone HT"
  ids:
    default: {}

seededConePuppiMHT:
  label: "SeededCone MHT"
  ids:
    default: {}

trackerHT:
  label: "Tracker HT"
  ids:
    default: {}

trackerMET:
  label: "Tracker MET"
  ids:
    default: {}

trackerMHT:
  label: "Tracker MHT"
  ids:
    default: {}
