gmtDispMuon:
  sample: MinBias
  version: V38nano
  test_objects:
    - L1gmtMuon:default
    - L1gmtDispMuon:default
  binning:
    min: 0
    max: 75
    step: 3

gmtDispMuonByRegion:
  sample: MinBias
  version: V38nano
  test_objects:
    # - L1gmtMuon:default
    # - L1gmtDispMuon:default
    - L1gmtDispMuon:default:barrel
    - L1gmtDispMuon:default:overlap
    - L1gmtDispMuon:default:endcap
  binning:
    min: 0
    max: 75
    step: 3