TauRates:
  sample: MinBias
  version: V29
  test_objects:
    - nnTau:default
    - caloTau:default
  binning:
    min: 10
    max: 155
    step: 5

TauRatesByRegion:
  sample: MinBias
  version: V29
  test_objects:
    - caloTau:default:barrel
    - caloTau:default:endcap
    - nnTau:default:barrel
    - nnTau:default:endcap
  binning:
    min: 10
    max: 155
    step: 5
