HtoLLPto4b_M125_Phi60_ctau100_promptHT:
  sample: HtoLLPto4b_M125_Phi60_ctau100
  version: V44nano
  reference_object:
    GenJet:ht_default: "pt"
  test_objects:
    L1puppiJetSC4sums:HT: "pt"
    L1TrackHT:HT: "ht"
    L1ExtTrackHT:HT: "ht"
  thresholds: [50, 100]
  # scalings:
  #   method: "naive"
  #   threshold: 0.90
  xlabel: "Gen. HT (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV)"
  binning:
    min: 0
    max: 750
    step: 20

# HtoLLPto4b_M125_Phi60_ctau100_dispHT:
#   sample: HtoLLPto4b_M125_Phi60_ctau100
#   version: V44nano
#   reference_object:
#     GenJet:ht_default: "pt"
#   test_objects:
#     L1puppiJetSC4sums:HT: "pt"
#     L1TrackHT:HT: "ht"
#     L1ExtTrackHT:HT: "ht"
#   thresholds: [350]
#   scalings:
#     method: "naive"
#     threshold: 0.90
#   xlabel: "Gen. HT (GeV)"
#   ylabel: "Trigger Efficiency (<threshold> GeV)"
#   binning:
#     min: 0
#     max: 750
#     step: 20
