JetMatchingBarrel:
  sample: TT
  version: V44nano
  match_test_to_ref: True
  reference_object:
    GenJet:jet_barrel: "pt"
    # cuts:
    #   event:
    #     - "abs({eta}) < 1.5"
    #   object:
    #     - "abs({eta}) < 2.4"
  test_objects:
    L1puppiJetHisto:default: "pt"
    L1puppiJetSC4:default: "pt"
    L1caloJet:default: "pt"
    L1TrackJet:default: "pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (barrel)"
  binning:
    min: 0
    max: 500
    step: 10

JetMatchingEndcap:
  sample: TT
  version: V44nano
  match_test_to_ref: True
  reference_object:
    GenJet:jet_endcap: "pt"
  test_objects:
    L1puppiJetHisto:default: "pt"
    L1puppiJetSC4:default: "pt"
    L1caloJet:default: "pt"
    L1TrackJet:default: "pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (<threshold> GeV, endcap)"
  binning:
    min: 0
    max: 500
    step: 10

JetMatchingForward:
  version: V44nano
  sample: TT
  match_test_to_ref: True
  reference_object:
    GenJet:jet_forward: "pt"
  test_objects:
    L1puppiJetHisto:default: "pt"
    L1puppiJetSC4:default: "pt"
    L1caloJet:default: "pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (<threshold> GeV, forward)"
  binning:
    min: 0
    max: 500
    step: 10


JetMatchingBarrelSC8:
  sample: TT
  version: V44nano
  match_test_to_ref: True
  reference_object:
    GenJetAK8:jet_barrel: "pt"
  test_objects:
    L1puppiJetSC8:default:barrel: "pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (<threshold> GeV, barrel)"
  binning:
    min: 0
    max: 500
    step: 10

JetMatchingEndcapSC8:
  sample: TT
  version: V44nano
  match_test_to_ref: True
  reference_object:
    GenJetAK8:jet_endcap: "pt"
  test_objects:
    L1puppiJetSC8:default:endcap: "pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (<threshold> GeV, endcap)"
  binning:
    min: 0
    max: 500
    step: 10
