JetMatching_Eta_Pt40To100_ExtendedVsRegular:
  sample: TT
  version: V44nano
  match_test_to_ref: True
  reference_object: 
    GenJet:reference_Pt40To100: "eta"
  test_objects:
    L1puppiJetSC4:default: "eta"
    L1puppiExtJetSC4:default: "eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (40-100 GeV)"
  binning:
    min: -5
    max: 5
    step: 0.25

JetMatching_Eta_Pt100ToInf_ExtendedVsRegular:
  sample: TT
  version: V44nano
  match_test_to_ref: True
  reference_object: 
    GenJet:reference_Pt100ToInf: "eta"
  test_objects:
    L1puppiJetSC4:default: "eta"
    L1puppiExtJetSC4:default: "eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (>100 GeV)"
  binning:
    min: -5
    max: 5
    step: 0.25

JetMatching_Eta_Pt30ToInf_genBJets:
  sample: TT
  version: V44nano
  match_test_to_ref: True
  reference_object: 
    GenJet:reference_Pt30ToInf_genBJets: "eta"
  test_objects:
    L1puppiExtJetSC4:bjetnn: "eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (>30 GeV)"
  binning:
    min: -2.4
    max: 2.4
    step: 0.25

JetMatching_Eta_Pt30ToInf_genNotBJets:
  sample: TT
  version: V44nano
  match_test_to_ref: True
  reference_object: 
    GenJet:reference_Pt30ToInf_genNotBJets: "eta"
  test_objects:
    L1puppiExtJetSC4:bjetnn: "eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (>30 GeV)"
  binning:
    min: -2.4
    max: 2.4
    step: 0.25

JetMatching_Pt_Pt30ToInf_genBJets:
  sample: TT
  version: V44nano
  match_test_to_ref: True
  reference_object: 
    GenJet:reference_Pt30ToInf_genBJets: "pt"
  test_objects:
    L1puppiExtJetSC4:bjetnn: "pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency"
  binning:
    min: 30
    max: 200
    step: 10

JetMatching_Pt_Pt30ToInf_genNotBJets:
  sample: TT
  version: V44nano
  match_test_to_ref: True
  reference_object: 
    GenJet:reference_Pt30ToInf_genNotBJets: "eta"
  test_objects:
    L1puppiExtJetSC4:bjetnn: "pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency"
  binning:
    min: 30
    max: 200
    step: 10
