MuonsTrigger_Barrel:
  sample: DYLL_M50
  version: V44nano
  match_test_to_ref: True
  reference_object:
    GenPart:muon_barrel: "eta"
  test_objects:
    L1gmtMuon:default:barrel: "pt"
    L1gmtTkMuon:default:barrel: "pt"
  xlabel: "Gen. pT (GeV)"
  ylabel: "Trigger Efficiency (barrel, L1 $p_T > 20$ GeV)"
  thresholds: [20, 25]
  scalings:
    method: "naive"
    threshold: 0.95
  binning:
    min: 0
    max: 50
    step: 1.5

MuonsTrigger_Overlap:
  sample: DYLL_M50
  version: V44nano
  match_test_to_ref: True
  reference_object:
    GenPart:muon_overlap: "eta"
  test_objects:
    L1gmtMuon:default:overlap: "pt"
    L1gmtTkMuon:default:overlap: "pt"
  xlabel: "Gen. pT (GeV)"
  ylabel: "Trigger Efficiency (overlap, L1 $p_T > 20$ GeV)"
  thresholds: [20, 25]
  scalings:
    method: "naive"
    threshold: 0.95
  binning:
    min: 0
    max: 50
    step: 1.5

MuonsTrigger_Endcap:
  sample: DYLL_M50
  version: V44nano
  match_test_to_ref: True
  reference_object:
    GenPart:muon_trigger_endcap: "eta"
  test_objects:
    L1gmtMuon:default:endcap: "pt"
    L1gmtTkMuon:default:endcap: "pt"
  xlabel: "Gen. pT (GeV)"
  ylabel: "Trigger Efficiency (endcap, L1 $p_T > 20$ GeV)"
  thresholds: [20, 25]
  scalings:
    method: "naive"
    threshold: 0.95
  binning:
    min: 0
    max: 50
    step: 1.5
