MuonTFsMatchingBarrel:
  sample: DYLL_M50
  version: V44nano
  match_test_to_ref: True
  reference_object:
    GenPart:muon:barrel_muon: "pt"
  test_objects:
    L1gmtMuon:default:barrel: "pt"
    L1MuonKMTF:default:barrel: "pt"
    L1MuonOMTF:default:barrel: "pt"
    L1MuonEMTF:default:barrel: "pt"
    L1gmtTkMuon:default:barrel: "pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (barrel)"
  binning:
    min: 0
    max: 100
    step: 3

MuonTFsMatchingOverlap:
  sample: DYLL_M50
  version: V44nano
  match_test_to_ref: True
  reference_object:
    GenPart:muon:overlap: "pt"
  test_objects:
    L1gmtMuon:default:overlap: "pt"
    L1MuonKMTF:default:overlap: "pt"
    L1MuonOMTF:default:overlap: "pt"
    L1MuonEMTF:default:overlap: "pt"
    L1gmtTkMuon:default:overlap: "pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (overlap)"
  binning:
    min: 0
    max: 100
    step: 3

MuonTFsMatchingEndcap:
  sample: DYLL_M50
  version: V44nano
  match_test_to_ref: True
  reference_object:
    GenPart:muon:endcap_muon: "pt"
  test_objects:
    L1gmtMuon:default:endcap: "pt"
    L1MuonKMTF:default:endcap: "pt"
    L1MuonOMTF:default:endcap: "pt"
    L1MuonEMTF:default:endcap: "pt"
    L1gmtTkMuon:default:endcap: "pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (endcap)"
  binning:
    min: 0
    max: 100
    step: 3
