MuonTFsMatching_Eta_Pt2to5:
  sample: DYLL_M50
  version: V44nano
  match_test_to_ref: True
  reference_object:
    GenPart:muon_Pt2to5: "eta"
  test_objects:
    L1gmtMuon:default: "eta"
    L1MuonKMTF:default: "eta" # Kalman filter (actually barrel) track finder
    L1MuonOMTF:default: "eta" # overlap track finder
    L1MuonEMTF:default: "eta" # endcap track finder
    L1gmtTkMuon:default: "eta" # gmt global muon trigger
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (2-5 GeV)"
  binning:
    min: -3
    max: 3
    step: 0.2

MuonTFsMatching_Eta_Pt15toInf:
  sample: DYLL_M50
  version: V44nano
  match_test_to_ref: True
  reference_object:
    GenPart:muon_Pt15toInf: "eta"
  test_objects:
    L1gmtMuon:default: "eta"
    L1MuonKMTF:default: "eta"
    L1MuonOMTF:default: "eta"
    L1MuonEMTF:default: "eta"
    L1gmtTkMuon:default: "eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (>15 GeV)"
  binning:
    min: -3
    max: 3
    step: 0.2
