PhotonsMatching_Eta_Pt10to25:
  sample: Hgg
  version: V44nano
  match_test_to_ref: True
  reference_object:
    GenPart:photon_Pt10to25: "eta"
  test_objects:
    L1EG:default: "eta"
    L1tkPhoton:NoIso: "eta"
    L1tkPhoton:Iso: "eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency ($10 < p_T < 25$ GeV)"
  binning:
    min: -3
    max: 3
    step: 0.2

PhotonsMatching_Eta_Pt25ToInf:
  sample: Hgg
  version: V44nano
  match_test_to_ref: True
  reference_object:
    GenPart:photon_Pt25toInf: "eta"
  test_objects:
    L1EG:default: "eta"
    L1tkPhoton:NoIso: "eta"
    L1tkPhoton:Iso: "eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency ($p_T > 25$ GeV)"
  binning:
    min: -3
    max: 3
    step: 0.2
