PhotonsMatching_Barrel:
  sample: Hgg
  version: V44nano
  match_test_to_ref: True
  reference_object:
    GenPart:photon_barrel: "pt" # TODO: Photon barrel region might be different from what is declared atm in GenPart
  test_objects:
    L1EG:default: "pt"
    L1tkPhoton:NoIso: "pt"
    L1tkPhoton:Iso: "pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (Barrel)"
  binning:
    min: 0
    max: 100
    step: 3

PhotonsMatching_Endcap:
  sample: Hgg
  version: V44nano
  match_test_to_ref: True
  reference_object:
    GenPart:photon_endcap: "pt"
  test_objects:
    L1EG:default: "pt"
    L1tkPhoton:NoIso: "pt"
    L1tkPhoton:Iso: "pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (Endcap)"
  binning:
    min: 0
    max: 100
    step: 3

# PhotonsMatching_Barrel_wPrunedGenParts:
#   sample: Hgg
#   version: V44nano
#   match_test_to_ref: True
#   reference_object:
#     object: "GenPart"
#     x_arg: "pt"
#     label: "Gen Photons"
#     cuts:
#       event:
#         - "(({statusFlags}>>7)&1) == 1"
#         - "abs({pdgId}) == 22"
#         - "abs({eta}) < 1.5"
#       object:
#         - "abs({eta}) < 2.4"
#   test_objects:
#     L1EG:default: "pt"
#     L1tkPhoton:NoIso: "pt"
#     L1tkPhoton:Iso: "pt"
#   xlabel: "Gen. $p_T$ (GeV)"
#   ylabel: "Matching Efficiency (Barrel)"
#   binning:
#     min: 0
#     max: 100
#     step: 3

# PhotonsMatching_Endcap_wPrunedGenParts:
#   sample: Hgg
#   version: V44nano
#   match_test_to_ref: True
#   reference_object:
#     object: "GenPart"
#     x_arg: "pt"
#     label: "Gen Photons"
#     cuts:
#       event:
#         - "(({statusFlags}>>7)&1) == 1"
#         - "abs({pdgId}) == 22"
#         - "abs({eta}) > 1.5"
#       object:
#         - "abs({eta}) < 2.4"
#   test_objects:
#     L1EG:default: "pt"
#     L1tkPhoton:NoIso: "pt"
#     L1tkPhoton:Iso: "pt"
#   xlabel: "Gen. $p_T$ (GeV)"
#   ylabel: "Matching Efficiency (Endcap)"
#   binning:
#     min: 0
#     max: 100
#     step: 3

# PhotonsMatching_Barrel_Pt30:
#   sample: Hgg
#   version: V44nano
#   match_test_to_ref: True
#   reference_object:
#     object: "GenPart"
#     x_arg: "pt"
#     label: "Gen Photons"
#     cuts:
#       event:
#         - "(({statusFlags}>>7)&1) == 1"
#         - "abs({pdgId}) == 22"
#         - "abs({eta}) < 1.5"
#       object:
#         - "abs({eta}) < 2.4"
#   test_objects:
#     L1EG:default: "pt"
#     L1tkPhoton:NoIso: "pt"
#     L1tkPhoton:Iso: "pt"
#     L1tkPhoton:NoIsoPt30: "pt"
#     L1tkPhoton:IsoPt30: "pt"
#   xlabel: "Gen. $p_T$ (GeV)"
#   ylabel: "Matching Efficiency (Barrel)"
#   binning:
#     min: 0
#     max: 150
#     step: 3

# PhotonsMatching_Endcap_Pt30:
#   sample: Hgg
#   version: V44nano
#   match_test_to_ref: True
#   reference_object:
#     object: "GenPart"
#     x_arg: "pt"
#     label: "Gen Photons"
#     cuts:
#       event:
#         - "(({statusFlags}>>7)&1) == 1"
#         - "abs({pdgId}) == 22"
#         - "abs({eta}) > 1.5"
#       object:
#         - "abs({eta}) < 2.4"
#   test_objects:
#     L1EG:default: "pt"
#     L1tkPhoton:NoIso: "pt"
#     L1tkPhoton:Iso: "pt"
#     L1tkPhoton:NoIsoPt30: "pt"
#     L1tkPhoton:IsoPt30: "pt"
#   xlabel: "Gen. $p_T$ (GeV)"
#   ylabel: "Matching Efficiency (Endcap)"
#   binning:
#     min: 0
#     max: 150
#     step: 3
