PhotonIsolation_Barrel:
  sample: Hgg
  version: V44nano
  iso_vs_efficiency: True
  match_test_to_ref: True
  reference_object:
    GenPart:photon:barrel: "pt"
  test_objects:
    L1tkPhoton:NoIso:barrel: "relIso"
  xlabel: "Isolation"
  ylabel: "Efficiency (Barrel)"
  binning:
    min: 0
    max: 0.5
    step: 0.005

PhotonIsolation_Endcap:
  sample: Hgg
  version: V44nano
  iso_vs_efficiency: True
  match_test_to_ref: True
  reference_object:
    GenPart:photon:endcap_photon: "pt" 
  test_objects:
    L1tkPhoton:NoIso:endcap: "relIso"
  xlabel: "Isolation"
  ylabel: "Efficiency (Endcap)"
  binning:
    min: 0
    max: 0.5
    step: 0.005

