TauMatching_Eta_Pt40To100:
  sample: VBFHToTauTau
  version: V44nano
  match_test_to_ref: True
  reference_object: 
    GenVisTau:tau_Pt40To100: "eta"
  test_objects:
    L1nnPuppiTau:default: "eta"
    L1hpsTau:default: "eta"
    L1caloTau:default: "eta"
    L1nnCaloTau:default: "eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (40-100 GeV)"
  binning:
    min: -3.0
    max: 3.0
    step: 0.2

TauMatching_Eta_Pt100ToInf:
  sample: VBFHToTauTau
  version: V44nano
  match_test_to_ref: True
  reference_object: 
    GenVisTau:tau_Pt100ToInf: "eta"
  test_objects:
    L1nnPuppiTau:default: "eta"
    L1hpsTau:default: "eta"
    L1caloTau:default: "eta"
    L1nnCaloTau:default: "eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (>100 GeV)"
  binning:
    min: -3
    max: 3
    step: 0.2
