TausMatchingBarrel:
  sample: VBFHToTauTau
  version: V44nano
  match_test_to_ref: True
  reference_object:
    GenVisTau:default:barrel: "pt"
  test_objects:
    L1nnPuppiTau:default: "pt"
    L1hpsTau:default: "pt"
    L1caloTau:default: "pt"
    L1nnCaloTau:default: "pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (Barrel)"
  binning:
    min: 0
    max: 150
    step: 6

TausMatchingEndcap:
  sample: VBFHToTauTau
  version: V44nano
  match_test_to_ref: True
  reference_object:
    GenVisTau:default:endcap: "pt"
  test_objects:
    L1nnPuppiTau:default: "pt"
    L1hpsTau:default: "pt"
    L1caloTau:default: "pt"
    L1nnCaloTau:default: "pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (Endcap)"
  binning:
    min: 0
    max: 150
    step: 6

