JetMatchingBarrel:
  sample: TT
  version: V32
  match_test_to_ref: True
  reference_object:
    object: "GenJet" # HACK -> using the nano GenJet parquet file here until fixing the menu ntuples
    x_arg: "pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({eta}) < 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    phase1PuppiJet:default: "Pt"
    seededConePuppiJet:default: "Pt"
    caloJet:default: "Pt"
    # trackerJet:default: "Pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (barrel)"
  binning:
    min: 0
    max: 500
    step: 10

JetMatchingEndcap:
  sample: TT
  version: V32
  match_test_to_ref: True
  reference_object:
    object: "GenJet" # HACK -> using the nano GenJet parquet file here until fixing the menu ntuples
    x_arg: "pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({eta}) > 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    phase1PuppiJet:default: "Pt"
    seededConePuppiJet:default: "Pt"
    caloJet:default: "Pt"
    # trackerJet:default: "Pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (endcap)"
  binning:
    min: 0
    max: 500
    step: 10

JetMatchingForward:
  version: V32
  sample: TT
  match_test_to_ref: True
  reference_object:
    object: "GenJet" # HACK -> using the nano GenJet parquet file here until fixing the menu ntuples
    x_arg: "pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({eta}) > 2.4"
      object:
        - "abs({eta}) < 5"
  test_objects:
    phase1PuppiJet:default: "Pt"
    seededConePuppiJet:default: "Pt"
    caloJet:default: "Pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (forward)"
  binning:
    min: 0
    max: 500
    step: 10
