MuonsMatching_Eta_Pt2to5:
  sample: DYLL_M50
  version: V32
  match_test_to_ref: True
  reference_object:
    object: "part_mu"
    x_arg: "Eta"
    label: "Gen Muons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "{pt} > 2"
        - "{pt} < 5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    gmtMuon:default: "Eta"
    gmtTkMuon:default: "Eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (2-5 GeV)"
  binning:
    min: -3
    max: 3
    step: 0.2

MuonsMatching_Eta_Pt15toInf:
  sample: DYLL_M50
  version: V32
  match_test_to_ref: True
  reference_object:
    object: "part_mu"
    x_arg: "Eta"
    label: "Gen Muons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "{pt} > 15"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    gmtMuon:default: "Eta"
    gmtTkMuon:default: "Eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (>15 GeV)"
  binning:
    min: -3
    max: 3
    step: 0.2
