PhotonsMatching_Eta_Pt10to25:
  sample: Hgg
  version: V32
  match_test_to_ref: True
  reference_object:
    object: "part_gamma"
    x_arg: "Eta"
    label: "Gen Photons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "{pt} < 25"
        - "{pt} > 10"
      object:
        - "abs({eta}) < 3.0"
  test_objects:
    EG:default: "Eta"
    tkPhoton:NoIso: "Eta"
    tkPhoton:Iso: "Eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency ($10 < p_T < 25$ GeV)"
  binning:
    min: -3
    max: 3
    step: 0.2

PhotonsMatching_Eta_Pt25toInf:
  sample: Hgg
  version: V32
  match_test_to_ref: True
  reference_object:
    object: "part_gamma"
    x_arg: "Eta"
    label: "Gen Photons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "{pt} >= 25"
      object:
        - "abs({eta}) < 3.0"
  test_objects:
    EG:default: "Eta"
    tkPhoton:NoIso: "Eta"
    tkPhoton:Iso: "Eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency ($10 < p_T < 25$ GeV)"
  binning:
    min: -3
    max: 3
    step: 0.2
