V22_V32_GMTMuonsBarrel_Comparison:
  files:
    MuonsTrigger_20_V22:
      object: gmtMuon
      dir: outputs/V22/turnons/
      label: "GMT Muon (V22)"
    MuonsTrigger_20_V32:
      object: gmtMuon
      dir: outputs/V32/turnons/
      label: "GMT Muon (V32)"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (Barrel)"
  watermark: "V22_V32_gmtMuonBarrel_Comp"
  save_dir: "outputs/V22vs27/turnons"

V22_V32_ElectronsBarrel_Comparison:
  files:
    ElectronsTriggerBarrel_30_V22:
      object: tkElectron
      dir: outputs/V22/turnons/
      label: "tkElectron (V22)"
    ElectronsTriggerBarrel_30_V32:
      object: tkElectron
      dir: outputs/V32/turnons/
      label: "tkElectron (V32)"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (Barrel)"
  watermark: "V22_V32_EGBarrel_Comp"
  save_dir: "outputs/V22vs27/turnons"

V22_V32_GMTtkMuonsBarrel_Comparison:
  files:
    MuonsTrigger_20_V22:
      object: gmtMuon
      dir: outputs/V22/turnons/
      label: "GMT tkMuon (V22)"
    MuonsTrigger_20_V32:
      object: gmtMuon
      dir: outputs/V32/turnons/
      label: "GMT tkMuon (V32)"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (Barrel)"
  watermark: "V22_V32_gmtTkMuonBarrel_Comp"
  save_dir: "outputs/V22vs27/turnons"
