ElectronsMatching_Eta_Pt10to25:
  sample: DYLL_M50
  version: V29
  match_test_to_ref: True
  reference_object:
    object: "part_e"
    x_arg: "Eta"
    label: "Gen Electrons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "{pt} < 25"
        - "{pt} > 10"
      object:
        - "abs({eta}) < 3.0"
  test_objects:
    EG:default: "Eta"
    tkElectron:NoIso: "Eta"
    tkElectron:NoIsoLowPt: "Eta"
    tkElectron:Iso: "Eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency ($10 < p_T < 25$ GeV)"
  binning:
    min: -3
    max: 3
    step: 0.2

ElectronsMatching_Eta_Pt25toInf:
  sample: DYLL_M50
  version: V29
  match_test_to_ref: True
  reference_object:
    object: "part_e"
    x_arg: "Eta"
    label: "Gen Electrons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "{pt} > 25"
      object:
        - "abs({eta}) < 3.0"
  test_objects:
    EG:default: "Eta"
    tkElectron:NoIso: "Eta"
    tkElectron:NoIsoLowPt: "Eta"
    tkElectron:Iso: "Eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency ($p_T > 25$ GeV)"
  binning:
    min: -3
    max: 3
    step: 0.2
