MHT30_90perc:
  sample: TT
  version: V29
  reference_object:
    object: "jet"
    x_arg: "Pt"
    label: "Gen MHT"
    cuts:
      object:
        - "abs({eta}) < 2.4"
        - "{pt} > 30"
    trafo: "MHT"
  test_objects:
    phase1PuppiMHT:default: "et"
    seededConePuppiMHT:default: "et"
  thresholds: [70, 150]
  scalings:
    method: "naive"
    threshold: 0.90
  xlabel: "Gen. MHT30 (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV)"
  binning:
    min: 0
    max: 500
    step: 20

MHT30_50perc:
  sample: TT
  version: V29
  reference_object:
    object: "jet"
    x_arg: "Pt"
    label: "Gen MHT"
    cuts:
      object:
        - "abs({eta}) < 2.4"
        - "{pt} > 30"
    trafo: "MHT"
  test_objects:
    phase1PuppiMHT:default: "et"
    seededConePuppiMHT:default: "et"
    trackerMHT:default: ""
  thresholds: [70, 150]
  scalings:
    method: "naive"
    threshold: 0.50
  xlabel: "Gen. MHT30 (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV)"
  binning:
    min: 0
    max: 500
    step: 20
