ElectronsTriggerBarrel:
  sample: DYLL_M50
  version: V32nano
  match_test_to_ref: True
  reference_object:
    object: "GenPart"
    x_arg: "pt"
    label: "Gen Electrons"
    cuts:
      event:
        - "(({statusFlags}>>7)&1) == 1"
        - "abs({pdgId}) == 11"
        - "abs({eta}) < 1.5"
      object:
        - "abs({eta}) < 2.8"
  test_objects:
    L1EG:default:barrel: "pt"
    L1tkElectron:NoIso:barrel: "pt"
    L1tkElectron:Iso:barrel: "pt"
  thresholds: [10, 20, 30, 40]
  scalings:
    method: "naive"
    threshold: 0.95
  xlabel: "Gen. pT (GeV)"
  ylabel: "Trigger Efficiency (barrel, L1 $p_T > <threshold>$ GeV)"
  binning:
    min: 0
    max: 100
    step: 1.5

ElectronsTriggerEndcap:
  sample: DYLL_M50
  version: V32nano
  match_test_to_ref: True
  reference_object:
    object: "GenPart"
    x_arg: "pt"
    label: "Gen Electrons"
    cuts:
      event:
        - "(({statusFlags}>>7)&1) == 1"
        - "abs({pdgId}) == 11"
        - "abs({eta}) > 1.5"
      object:
        - "abs({eta}) < 2.8"
  test_objects:
    L1EG:default:endcap: "pt"
    L1tkElectron:NoIso:endcap: "pt"
    L1tkElectron:Iso:endcap: "pt"
  thresholds: [10, 20, 30, 40]
  scalings:
    method: "naive"
    threshold: 0.95
  xlabel: "Gen. pT (GeV)"
  ylabel: "Trigger Efficiency (endcap, L1 $p_T > <threshold>$ GeV)"
  binning:
    min: 0
    max: 100
    step: 1.5

# ElectronsTriggerBarrel_wPrunedGenPart:
#   sample: DYLL_M50
#   version: V32nano
#   match_test_to_ref: True
#   reference_object:
#     object: "prunedGenPart"
#     x_arg: "pt"
#     label: "Gen Electrons"
#     cuts:
#       event:
#         - "(({statusFlags}>>7)&1) == 1"
#         - "abs({pdgId}) == 11"
#         - "abs({eta}) < 1.5"
#       object:
#         - "abs({eta}) < 2.8"
#   test_objects:
#     L1EG:default:barrel: "pt"
#     L1tkElectron:NoIso:barrel: "pt"
#     L1tkElectron:Iso:barrel: "pt"
#   thresholds: [10, 20, 30, 40]
#   scalings:
#     method: "naive"
#     threshold: 0.95
#   xlabel: "Gen. pT (GeV)"
#   ylabel: "Trigger Efficiency (barrel, L1 $p_T > <threshold>$ GeV)"
#   binning:
#     min: 0
#     max: 100
#     step: 1.5

# ElectronsTriggerEndcap_wPrunedGenPart:
#   sample: DYLL_M50
#   version: V32nano
#   match_test_to_ref: True
#   reference_object:
#     object: "prunedGenPart"
#     x_arg: "pt"
#     label: "Gen Electrons"
#     cuts:
#       event:
#         - "(({statusFlags}>>7)&1) == 1"
#         - "abs({pdgId}) == 11"
#         - "abs({eta}) > 1.5"
#       object:
#         - "abs({eta}) < 2.8"
#   test_objects:
#     # L1EG:default:endcap: "pt"
#     L1tkElectron:NoIso:endcap: "pt"
#     L1tkElectron:Iso:endcap: "pt"
#   thresholds: [10, 20, 30, 40]
#   scalings:
#     method: "naive"
#     threshold: 0.95
#   xlabel: "Gen. pT (GeV)"
#   ylabel: "Trigger Efficiency (endcap, L1 $p_T > <threshold>$ GeV)"
#   binning:
#     min: 0
#     max: 100
#     step: 1.5
