PhotonIsolation_Barrel:
  sample: Hgg
  version: V32nano
  iso_vs_efficiency: True
  match_test_to_ref: True
  reference_object:
    object: "part_gamma"
    x_arg: "pt"
    label: "Gen Photons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "abs({eta}) < 1.479"
      object:
        - "abs({eta}) < 1.479"
  test_objects:
    L1tkPhoton:NoIso:barrel: "relIso"
  xlabel: "Isolation"
  ylabel: "Efficiency (Barrel)"
  binning:
    min: 0
    max: 0.5
    step: 0.005

PhotonIsolation_Endcap:
  sample: Hgg
  version: V32nano
  iso_vs_efficiency: True
  match_test_to_ref: True
  reference_object:
    object: "part_gamma"
    x_arg: "pt"
    label: "Gen Photons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "abs({eta}) > 1.479"
        - "abs({eta}) < 2.4"
      object:
        - "abs({eta}) > 1.479"
  test_objects:
    L1tkPhoton:NoIso:endcap: "relIso"
  xlabel: "Isolation"
  ylabel: "Efficiency (Endcap)"
  binning:
    min: 0
    max: 0.5
    step: 0.005

