# GenTau_TausMatchingBarrel_highPt:
#   sample: VBFHToTauTau
#   version: V43nano
#   match_test_to_ref: True
#   reference_object:
#     object: "GenPart"
#     x_arg: "pt"
#     label: "Gen Taus"
#     cuts:
#       event:
#         - "(({statusFlags}>>7)&1) == 1"
#         - "abs({pdgId}) == 15"
#         - "abs({eta}) < 1.5"
#       object:
#         - "abs({eta}) < 2.4"
#   test_objects:
#     L1nnPuppiTau:default: "pt"
#     L1hpsTau:default: "pt"
#     L1caloTau:default: "pt"
#     L1nnCaloTau:default: "pt"
# #     L1caloTau:PtGe20: "Pt"
#   xlabel: "Gen. $p_T$ (GeV)"
#   ylabel: "Matching Efficiency (Barrel)"
#   binning:
#     min: 0
#     max: 400
#     step: 20

# GenTau_TausMatchingEndcap_highPt:
#   sample: VBFHToTauTau
#   version: V43nano
#   match_test_to_ref: True
#   reference_object:
#     object: "GenPart"
#     x_arg: "pt"
#     label: "Gen Taus"
#     cuts:
#       event:
#         - "(({statusFlags}>>7)&1) == 1"
#         - "abs({pdgId}) == 15"
#         - "abs({eta}) > 1.5"
#       object:
#         - "abs({eta}) < 2.4"
#   test_objects:
#     L1nnPuppiTau:default: "pt"
#     L1hpsTau:default: "pt"
#     L1caloTau:default: "pt"
#     L1nnCaloTau:default: "pt"
# #     L1caloTau:PtGe20: "Pt"
#   xlabel: "Gen. $p_T$ (GeV)"
#   ylabel: "Matching Efficiency (Endcap)"
#   binning:
#     min: 0
#     max: 400
#     step: 20

# # GenTau_# TauTriggerBarrel_90perc_highPt:
# #   sample: VBFHToTauTau
# #   version: V43nano
# #   match_test_to_ref: True
# #   reference_object:
# #     object: "GenPart"
# #     x_arg: "pt"
# #     label: "Gen Taus"
# #     cuts:
#       # event:
#       #   - "(({statusFlags}>>7)&1) == 1"
#       #   - "abs({pdgId}) == 15"
#   #        - "abs({eta}) < 1.5"
# #       object:
# #         - "abs({eta}) < 2.4"
# #   test_objects:
# #     L1nnPuppiTau:default:barrel: "pt"
# #     L1hpsTau:default:barrel: "pt"
# #     L1caloTau:default:barrel: "pt"
# #     L1nnCaloTau:default:barrel: "pt"
# #   xlabel: "Gen. pT (GeV)"
# #   ylabel: "Trigger Efficiency (barrel, L1 $p_T > <threshold>$ GeV)"
# #   thresholds: [30, 50]
# #   # scalings:
# #   #   method: "naive"
# #   #   threshold: 0.90
# #   binning:
# #     min: 0
# #     max: 400
# #     step: 10

# # GenTau_# TauTriggerEndcap_90perc_highPt:
# #   sample: VBFHToTauTau
# #   version: V43nano
# #   match_test_to_ref: True
# #   reference_object:
# #     object: "GenPart"
# #     x_arg: "pt"
# #     label: "Gen Taus"
# #     cuts:
#       # event:
#       #   - "(({statusFlags}>>7)&1) == 1"
#       #   - "abs({pdgId}) == 15"
#   #        - "abs({eta}) > 1.5"
# #       object:
# #         - "abs({eta}) < 2.4"
# #   test_objects:
# #     L1nnPuppiTau:default:endcap: "pt"
# #     L1hpsTau:default:endcap: "pt"
# #     L1caloTau:default:endcap: "pt"
# #     L1nnCaloTau:default:endcap: "pt"
# #   xlabel: "Gen. pT (GeV)"
# #   ylabel: "Trigger Efficiency (endcap, L1 $p_T > <threshold>$ GeV)"
# #   thresholds: [30, 50]
# #   # scalings:
# #   #   method: "naive"
# #   #   threshold: 0.90
# #   binning:
# #     min: 0
# #     max: 400
# #     step: 10
