GenJetAK8:
  label: "Gen AK8 Jets"
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.5]
    endcap: [1.5, 2.4]
    forward: [2.4, 5]
  ids:
    jet_matching_SC8_Pt100ToInf:
      cuts:
        object:
        # event:
          inclusive:
            - "{pt} > 100"
      # object:
        # inclusive:
            - "abs({eta}) < 5"
    jet_barrel:
      cuts:
        object:
        # event:
          inclusive:
            - "abs({eta}) < 1.5"
        # object:
          # inclusive:
            - "abs({eta}) < 2.4"
    jet_endcap:
      cuts:
        object:
        # event:
          inclusive:
            - "abs({eta}) > 1.5"
        # object:
          # inclusive:
            - "abs({eta}) < 2.4"
    jet_forward:
      cuts:
        object:
        # event:
          inclusive:
            - "abs({eta}) > 2.4"
        # object:
          # inclusive:
            - "abs({eta}) < 5"


GenJet:
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.5]
    endcap: [1.5, 2.4]
    forward: [2.4, 5]
  ids:
    mht_default:
      label: "Gen MHT"
      trafo: "MHT"
      cuts:
        object:
          inclusive:
            - "abs({eta}) < 2.4"
            - "{pt} > 30"
    ht_default:
      label: "Gen HT"
      trafo: "HT"
      cuts:
        object:
          inclusive:
            - "abs({eta}) < 2.4"
            - "{pt} > 30"
    jet_Pt40To100:
      label: "Gen Jets"
      cuts:
        object:
          inclusive:
            - "{pt} > 40"
            - "{pt} < 100"
          # object:
            # inclusive:
            - "abs({eta}) < 5"
    jet_Pt100ToInf:
      label: "Gen Jets"
      cuts:
        object:
        # event:
          inclusive:
            - "{pt} > 100"
          # object:
            # inclusive:
            - "abs({eta}) < 5"
    jet_Pt100ToInf_extEta:
      label: "Gen Jets"
      cuts:
        object:
        # event:
          inclusive:
            - "{pt} > 100"
        # object:
          # inclusive:
            - "abs({eta}) < 7"
    jet_Pt30ToInf_genBJets:
      label: "Gen Jets"
      cuts:
        object: 
        # event:
          inclusive:
            - "{pt} > 30"
            - "abs({partonFlavour}) == 5"
        # object:
          # inclusive:
            - "abs({eta}) < 2.4"
    jet_Pt30ToInf_genNotBJets:
      label: "Gen Jets"
      cuts:
        object:
        # event:
          inclusive:
            - "{pt} > 30"
            - "abs({partonFlavour}) != 5"
        # object:
          # inclusive:
            - "abs({eta}) < 2.4"
    jet_barrel:
      label: "Gen Jets"
      cuts:
        object:
          # event:
          inclusive:
            - "abs({eta}) < 1.5"
        # object:
          # inclusive:
            - "abs({eta}) < 2.4"
    jet_endcap:
      label: "Gen Jets"
      cuts:
        object:
        # event:
          inclusive:
            - "abs({eta}) > 1.5"
        # object:
          # inclusive:
            - "abs({eta}) < 2.4"
    jet_forward:
      label: "Gen Jets"
      cuts:
        object:
          # event:
            inclusive:
              - "abs({eta}) > 2.4"
          # object:
            # inclusive:
              - "abs({eta}) < 5"

L1caloJet:
  match_dR: 0.3
  label: "Calo Jet"
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.5]
    endcap: [1.5, 2.4]
    forward: [2.4, 5]
  cuts:
    inclusive:
      - "abs({eta}) < 7"
  ids:
    default:
      cuts:
        inclusive:
          - "abs({eta}) < 7"

L1puppiExtJetSC4:
  match_dR: 0.35
  label: "Seeded Cone Extended PuppiJet"
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.5]
    endcap: [1.5, 2.4]
    forward: [2.4, 5]
  ids:
    default:
      cuts:
        inclusive:
          - "abs({eta}) < 5"
    PtGe25:
        cuts:
          inclusive:
            - "abs({eta}) < 7"
            - "abs({pt}) >= 25"
    bjetnn:
      label: "SC Extended PuppiJet, BtagScore > 0.71"
      cuts:
        inclusive:
          - "abs({eta}) < 2.4"
          - "{btagScore} > 0.71"

L1puppiJetHisto:
  match_dR: 0.3
  label: "Histogrammed PuppiJet"
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.5]
    endcap: [1.5, 2.4]
    forward: [2.4, 5]
  ids:
    default:
      cuts:
        inclusive:
          - "abs({eta}) < 7"

L1puppiJetSC4:
  match_dR: 0.35
  label: "Seeded Cone PuppiJet"
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.5]
    endcap: [1.5, 2.4]
    forward: [2.4, 5]
  ids:
    default:
      cuts:
        inclusive:
          - "abs({eta}) < 7"
    PtGe25:
        cuts:
          inclusive:
            - "abs({eta}) < 7"
            - "abs({pt}) >= 25"

L1puppiJetSC8:
  match_dR: 0.35
  label: "Seeded Cone PuppiJet 8"
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.5]
    endcap: [1.5, 2.4]
    forward: [2.4, 5]
  ids:
    default:
      cuts:
        inclusive:
          - "abs({eta}) < 7"

L1TrackJet:
  match_dR: 0.4
  label: "Tracker Jet"
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.5]
    endcap: [1.5, 2.4]
  ids:
    default:
      cuts:
        inclusive:
          - "abs({eta}) < 7"


